# Params related to model initialization & data preprocessing
# e.g. directly affecting the (inference) usage & behavior of the model
model_hparams:
  model_name: "downstream"
  model_suffix: ""
  imu_encoder_name: "prnn"
  video_encoder_name: "clip_1frame"
  window_sec: 2.5
  target_fps: 10
  narration_cleaner: True

# Params for the trainer
train_hparams:
  # For downstream tasks, only a single modality is supported for now
  list_modalities: 
    - "imu"
  limit_train_batches: 1.0
  batch_size: 32
  max_epochs: 10
  gpus: 1
  num_workers_for_dm: 10
  test_only: False
  trainer_strategy: "ddp"
  freeze_modality: False
  path_load_pretrained_imu_encoder: "/home/pranayr_umass_edu/imu2clip/saved/prnn/i2c/i2c_s_i_t_t_se_prnn_w_2.5_master_src_encoder.pt"
